version: '3'
services:
  web:
    build: ./backend
    ports:
      - "5000:5000"
  mongo:
    image: "mongo:3.6.8-stretch"
  mongo-express:
    image: "mongo-express:latest"
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=puyo
      - ME_CONFIG_BASICAUTH_PASSWORD=tetris
